# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: XSD Quality Gate

on:
  push:
    branches: [ "schematron-poc" ]
  pull_request:
    branches: [ "schematron-poc" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Display environment
      run: |
        echo What is in this directory?
        ls -l 
        echo 
        echo What is in the ./src directory?
        ls -l ./src 
        echo
        echo Is Python installed?
        python --version
        echo Is Java installed?
        java --version
        echo
        echo Is Git installed~?
        git --version
        echo
        echo What about build tools?
        mvn --version

    - name: QualityGate
      run: mvn clean test
